# Generated by Django 3.0.5 on 2020-04-07 22:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to=inventory.models.upload_location)),
                ('barcode', models.CharField(blank=True, editable=False, max_length=25)),
                ('barcodeImage', models.ImageField(blank=True, editable=False, upload_to='barcodes/')),
                ('status', models.CharField(choices=[('Check-in', 'Check-in'), ('Check-out', 'Check-out')], default='Check-in', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Vender_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Item')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Vender')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField()),
                ('date_purchased', models.DateField(blank=True, default=datetime.datetime.now)),
                ('total_price', models.FloatField(help_text='in Rupees eg: 5000')),
                ('advance', models.FloatField(blank=True, help_text='in Rupees eg: 200')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=10)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Employee')),
                ('vender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Vender')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField()),
                ('date_ordered', models.DateField(blank=True, default=datetime.datetime.now)),
                ('total_price', models.FloatField(help_text='eg: 5000')),
                ('advance', models.FloatField(blank=True, help_text='eg: 200')),
                ('adjustment', models.FloatField(blank=True, help_text='eg: +200 or -200')),
                ('discount', models.FloatField(blank=True, help_text='eg: 300')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=10)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Customer')),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Subcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Warehouse'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.IntegerField()),
                ('date_added', models.DateField(blank=True, default=datetime.datetime.now)),
                ('total_price', models.FloatField(help_text='eg: 5000')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Invoiced', 'Invoiced')], max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Location'),
        ),
    ]
