# Generated by Django 3.0.5 on 2020-04-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_demand_items_order_items_purchase_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='state',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
