# Generated by Django 3.0.5 on 2020-04-08 04:17

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200408_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand_items',
            name='bundels',
        ),
        migrations.RemoveField(
            model_name='purchase_items',
            name='bundels',
        ),
        migrations.AddField(
            model_name='demand_items',
            name='bundles',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='purchase_items',
            name='bundles',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Location'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand_items',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcodeImage',
            field=models.ImageField(blank=True, editable=False, max_length=200, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=inventory.models.upload_location),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Subcategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adjustment',
            field=models.FloatField(blank=True, help_text='eg: +200 or -200', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='advance',
            field=models.FloatField(blank=True, help_text='eg: 200', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, help_text='eg: 300', null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='bundles',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='advance',
            field=models.FloatField(blank=True, help_text='in Rupees eg: 200', null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_items',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vender',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
