# Generated by Django 3.0.5 on 2020-04-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200408_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barcodeImage',
        ),
    ]
