# Generated by Django 3.0.5 on 2020-04-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_item_barcodeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcodeImage',
            field=models.ImageField(blank=True, max_length=200, upload_to='barcodes/'),
        ),
    ]
