# Generated by Django 3.0.5 on 2020-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20200408_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcodeImage',
            field=models.ImageField(blank=True, max_length=200, upload_to='barcodes/'),
        ),
    ]
