# Generated by Django 3.0.5 on 2020-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20200410_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
