# Generated by Django 3.0.5 on 2020-05-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20200515_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='employee',
        ),
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=30)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Location')),
            ],
        ),
    ]
