# Generated by Django 3.0.5 on 2020-05-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20200527_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Warehouse'),
        ),
    ]
