# Generated by Django 3.0.5 on 2020-06-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20200602_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
