# Generated by Django 3.0.5 on 2020-06-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20200605_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
