# Generated by Django 3.0.5 on 2020-06-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20200609_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='date_added',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
